# Generated by Django 3.2.3 on 2021-05-19 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_addprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addprofile',
            new_name='Profile',
        ),
    ]
