# Generated by Django 3.2.3 on 2021-05-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_on_blog',
        ),
    ]
