# Generated by Django 3.2.3 on 2021-05-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_comment_on_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_on_blog',
        ),
    ]
