# Generated by Django 3.2.3 on 2021-05-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
