# Generated by Django 3.2.3 on 2021-05-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210527_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='followers_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='following_user',
        ),
    ]
