# Generated by Django 3.2.3 on 2021-05-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210529_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
