# Generated by Django 3.2.3 on 2021-06-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20210627_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='', upload_to='media/coverpic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='', upload_to='media/profilepic'),
        ),
    ]
